language: go

os:
  - linux

before_install:
  - sudo apt-get update
  - sudo apt-get install -y qemu-user-static

go:
  - "1.11"
  - "1.10"
  - "1.9"

script:
  - GOOS=linux GOARCH=mips64 go test -c -o bitset.test
  - go test ./... -v
  - qemu-mips64-static ./bitset.test -test.v
